# Site settings
title:          想象力做功
description:    "What you know about computing other people will learn."
url:            https://github.com/inelaah/rain

# Author
author:
  name:         jiriyu
  email:        jiriyu98@gmail.com
  url:          https://github.com/jiriyu98

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# multi-languages
language_default: zh # default language
languages_colletction: ["en", "zh", "jp"] # multi-languages

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  resume: /aboutme
  # email: jiriyu98@gmail.com
  github: https://github.com/jiriyu98
  # twitter: 
  # linkedin: https://www.linkedin.com/in/jiriyu/
